#!/bin/bash

# Cache
if [ -n "$XDG_CACHE_HOME" ]; then
   CACHE_DIR="$XDG_CACHE_HOME/vifm/preview"
else
   CACHE_DIR="$HOME/.cache/vifm/preview"
fi

# Log
LOG_ENABLED=1 # 0: No logging | 1: Logging (cause timeloss)

# Preview command
SHOW_CMD_TEMPLATE='kitten icat --clear --stdin=no --place=%pwx%ph@%pxx%py --scale-up --transfer-mode=file "%file" >%tty <%tty'
CLEAR_CMD_TEMPLATE='kitten icat --clear --silent %N >%tty <%tty &'

# Images
IMAGE_QUALITY=80
IMAGE_SIZE="600x600" # {width}x{height} of vifm window on full screen

# Videos
VIDEO_QUALITY=80   # quality for thumbnail image
VIDEO_SEEK_TIME=10 # seek time to get thumbnail (percentage)
VIDEO_SIZE="640"   # {width}, for ffmpegthumbnailer

# legacy settings for ffmpeg
# VIDEO_FRAME=1000     # frame num for cut, for ffmpeg
# VIDEO_SIZE="640:360" # {width}:{height}, for ffmpeg
