#!/bin/bash

SCRIPT_NAME='preview.vifm'

# --------------------------------------------------------------------------------
# Functions
# --------------------------------------------------------------------------------

# Loging
Log() {
   local subcmd=$1
   local category="$2"
   local value="$3"
   local subcmd_len=8
   local category_len=15
   if [[ $LOG_ENABLED -eq 0 ]]; then
      printf "[ %-${subcmd_len}s ] %-${category_len}s: %s\n" "$subcmd" "$category" "$value" >>"$LOG_PATH"
   fi
}

GetHash() {
   local path="$1"
   local hash=$(realpath "$path" | sha256sum | cut -d' ' -f1)
   echo "$hash"
}

GetParentDir() {
   local path="$1"
   local parent=$(dirname "$path")
   echo "$parent"
}

GetMtime() {
   local path="$1"
   local timestamp=$(date -r "$path" +"%s")
   echo $timestamp
}

GetStatus() {
   local path="$1"
   local action=$2
   local hash=$(GetHash "$path")

   local hash_filename
   if [[ -d "$path" ]]; then # directory
      hash_filename="$CACHE_DIR/$hash.dir.$action"
   elif [[ -f "$path" ]]; then # file
      hash_filename="$CACHE_DIR/$hash.jpg"
   fi
   if [[ -f "$hash_filename" ]]; then
      echo "done"
   elif [[ -f "$hash_filename.lock" ]]; then
      echo "locked"
   else
      echo "none"
   fi
}

SetStatus() {
   local path="$1"
   local action=$2
   local status=$3
   local hash=$(GetHash "$path")

   if [[ -d "$path" ]]; then # directory
      local hash_filename="$CACHE_DIR/$hash.dir.$action"
      if [[ "$status" == "done" ]]; then
         rm -f "$hash_filename.lock"
         touch "$hash_filename"
      elif [[ "$status" == "locked" ]]; then
         touch "$hash_filename.lock"
      elif [[ "$status" == "none" ]]; then
         rm -f "$hash_filename"
      fi
   elif [[ -f "$path" ]]; then # file
      local hash_filename="$CACHE_DIR/$hash.jpg"
      if [[ "$status" == "done" ]]; then
         rm -f "$hash_filename.lock"
         # touch "$hash_filename" # Do not overwrite the preview file
      elif [[ "$status" == "locked" ]]; then
         touch "$hash_filename.lock"
      elif [[ "$status" == "none" ]]; then
         rm -f "$hash_filename"
      fi
   fi
}

GetEnvironment() {
   local env=""
   [ -n "$NVIM" ] && env="$env nvim"
   [ -n "$TMUX" ] && env="$env tmux"
   [ -z "$TMUX" ] && env="$env terminal"
   echo "${env# }" # (e.g. "nvim tmux")
}

IsContained() {
   local source="$1"
   local target="$2"

   for t in $target; do
      case " $source " in
      *" $t "*) ;;
      *) return 1 ;;
      esac
   done
   return 0
}

# Generate preview & return the hash path
GeneratePreview() {
   local action=$1
   local path="$2"
   local force=$3

   Log "$action" "generate" "(start) path='$path'"

   # Get preview filename (hash)
   local hash=$(GetHash "$path")
   local preview_path="$CACHE_DIR/$hash.jpg"

   # Get timestamp
   local preview_mtime=$(GetMtime "$preview_path")
   local path_mtime=$(GetMtime "$path")

   # Conditions
   local preview_missing=1
   local preview_older=1
   local force_update=1

   [[ ! -f "$preview_path" ]] && preview_missing=0
   [[ "$preview_mtime" -lt "$path_mtime" ]] && preview_older=0
   [[ "$force" == "force" ]] && force_update=0

   # Generate preview
   if [[ $preview_missing || $preview_older || $force_update ]]; then
      [[ $preview_missing ]] && Log "$action" "generate" "preview_missing=$preview_older)"
      [[ $preview_older ]] && Log "$action" "generate" "preview_older=$preview_older)"
      [[ $preview_older ]] && Log "$action" "generate" "force_update=$force_update)"
      if [[ $action == "image" ]]; then
         # magick "$file" -quality $IMAGE_QUALITY -resize $IMAGE_SIZE $COLOR_SPACE "$preview_path" &>/dev/null # '&' at last works async ?
         local colorspace=$(magick identify -format "%[colorspace]" "$path" 2>/dev/null)

         if [[ $colorspace == "CMYK" && $IMAGE_COLORSPACE_CMYK_TO_SRGB -eq 0 ]]; then
            magick "$path" -quality $IMAGE_QUALITY -resize $IMAGE_SIZE -colorspace sRGB "$preview_path" &>/dev/null
         else
            magick "$path" -quality $IMAGE_QUALITY -resize $IMAGE_SIZE "$preview_path" &>/dev/null
         fi
         Log "$action" "generate" "'magick' processed '$path'"
      elif [[ $action == "video" ]]; then
         # ffmpeg -y -i "$file" -vf "select='eq(n,$VIDEO_FRAME)',scale=$VIDEO_SIZE" -frames:v 1 "$preview_path" &>/dev/null
         ffmpegthumbnailer -s $VIDEO_SIZE -q $VIDEO_QUALITY -t $VIDEO_SEEK_TIME -i "$path" -o "$preview_path" &>/dev/null
         Log "$action" "generate" "'ffmpegthumbnailer' processed '$path'"
      else
         Log "$action" "generate" "ERROR '$action' is not a valid action."
      fi
   fi

   Log "$action" "generate" "(end) preview_path='$preview_path'"
   echo $preview_path
}

# Generate previews for all matched files in dir
GeneratePreviewAll() {
   local action=$1
   local dir="$2"
   local patterns="$3"
   local force="$4"

   local cnt=0

   Log "$action" "generate_all" "(start) dir='$dir'"

   local status=$(GetStatus "$dir" "$action")
   if [[ $status == "done" && "$force" != "force" ]]; then
      Log "$action" "generate_all" "(info) Skipped generating all in '$dir' (already generated)"
      return 1
   elif [[ $status == "locked" ]]; then
      Log "$action" "generate_all" "(info) Skipped generating all in '$dir' (generating now)"
      return 1
   fi

   SetStatus "$dir" "$action" "locked"

   # List files in the directory and loop through each pattern
   IFS=',' read -r -a pat_array <<<"$patterns"
   local jobs=()
   for pat in "${pat_array[@]}"; do
      Log "$action" "generate_all" "pat='$pat'"
      # For each pattern, find matching files
      for file in "$dir"/$pat; do
         # Only proceed if $file is a regular file
         if [[ -f "$file" ]]; then
            local file_abspath=$(realpath "$file")
            if [[ "$file_abspath" == "$TARGET_ABSPATH" ]]; then # Exclude current file
               Log "$action" "generate_all" "(info) Skipped current file. file_abspath='$file_abspath'"
            else
               Log "$action" "generate_all" "file_abspath='$file_abspath'"
               GeneratePreview $action "$file_abspath" $force &
               ((cnt++))
            fi
         fi
      done
   done

   wait

   SetStatus "$dir" "$action" "done"
   Log "$action" "generate_all" "(end) processed $cnt files in '$dir'"
}

# Replace % placeholders to actual values
GetCmd() {
   local cmd="$1"
   local preview_path="$2"

   # Replace
   cmd="${cmd//%pw/$PW}"
   cmd="${cmd//%ph/$PH}"
   cmd="${cmd//%px/$PX}"
   cmd="${cmd//%py/$PY}"
   cmd="${cmd//%tty/$VIFM_PREVIEW_TTY}"
   if [[ $preview_path != '' ]]; then
      cmd="${cmd//%file/$preview_path}"
   fi

   Log "$ACTION" "get_cmd" "cmd='$cmd'"
   echo "$cmd"
}

# Clear
Clear() {
   Log "$ACTION" "clear" "(start)"
   local cmd_clear=$(GetCmd "$CLEAR_CMD_TEMPLATE" "")
   sh -c "$cmd_clear"
   Log "$ACTION" "clear" "(end)"
}

# Show preview
Show() {
   local path="$1"
   Log "$ACTION" "show" "(start) path='$path'"
   # Adjust x,y on nvim
   if [[ $IS_NVIM ]]; then
      PX=$((PX + VIFM_PREVIEW_WIN_X + VIFM_PREVIEW_WIN_BORDER_WIDTH))
      PY=$((PY + VIFM_PREVIEW_WIN_Y + VIFM_PREVIEW_WIN_BORDER_WIDTH))
   fi
   local cmd_show=$(GetCmd "$SHOW_CMD_TEMPLATE" "$path")
   sh -c "$cmd_show"
   Log "$ACTION" "show" "(end)"
}

#  ╭────────────────────────────────────────────────────────────────╮
#  │                          Main script                           │
#  ╰────────────────────────────────────────────────────────────────╯
Main() {
   # Logging
   Log "$ACTION" "main" "(start) ----------------------------------------------------------"
   if [[ "$ACTION" != "clear" ]]; then
      Log "$ACTION" "ctx" "TARGET_PATH=$TARGET_PATH"
      Log "$ACTION" "ctx" "PWxPH=$PWx$PH PXxPY=$PXx$PY"
   fi
   Log "$ACTION" "ctx" "ENV='$ENV'"
   if [[ $IS_NVIM -eq 0 ]]; then
      Log "$ACTION" "ctx" "VIFM_PREVIEW_WIN X=$VIFM_PREVIEW_WIN_X Y=$VIFM_PREVIEW_WIN_Y BORDER_WIDTH=$VIFM_PREVIEW_WIN_BORDER_WIDTH"
   fi

   # Create cache directory
   mkdir -p "$CACHE_DIR"

   # Execute actions
   if [[ $ACTION == "clear" ]]; then
      # clear
      Clear
   elif [[ $ACTION == "dir" ]]; then
      # (Legacy) Generate preview files for all images|videos in dir in background
      GeneratePreviewAll image "$TARGET_ABSPATH" $IMAGE_PATTERNS >/dev/null 2>&1 &
      GeneratePreviewAll video "$TARGET_ABSPATH" $VIDEO_PATTERNS >/dev/null 2>&1 &
   elif [[ $ACTION == "image" ]]; then
      # Generate preview files for all images in parent dir in background
      GeneratePreviewAll $ACTION "$PARENT" $IMAGE_PATTERNS >/dev/null 2>&1 &
      # Preview a image
      local preview_path=$(GeneratePreview $ACTION "$TARGET_ABSPATH" $IMAGE_PATTERNS)
      Show "$preview_path"
   elif [[ $ACTION == "video" ]]; then
      # Generate preview files for all videos in parent dir in background
      GeneratePreviewAll $ACTION "$PARENT" $VIDEO_PATTERNS >/dev/null 2>&1 &
      # Preview a video
      local preview_path=$(GeneratePreview $ACTION "$TARGET_ABSPATH" $VIDEO_PATTERNS)
      Show "$preview_path"
   elif [[ $ACTION == "refresh" ]]; then
      GeneratePreviewAll image "$TARGET_ABSPATH" $IMAGE_PATTERNS "force" >/dev/null 2>&1 &
      GeneratePreviewAll video "$TARGET_ABSPATH" $VIDEO_PATTERNS "force" >/dev/null 2>&1 &
   elif [[ $ACTION == "delete" ]]; then
      rm -f "$CACHE_DIR"/*
   fi
   Log "$ACTION" "main" "(end)"
}

#  ╭────────────────────────────────────────────────────────────────╮
#  │                        Global variables                        │
#  ╰────────────────────────────────────────────────────────────────╯
# Parse command line args
ACTION=$1
TARGET_PATH=$2
PW=$3
PH=$4
PX=$5
PY=$6

# Adjust target path
TARGET_PATH="${TARGET_PATH//\\ / }" # replate '\ ' to ' '

# Get abs path
TARGET_ABSPATH=$(realpath "$TARGET_PATH")

# Get Parent dir
PARENT=$(GetParentDir "$TARGET_ABSPATH")

# Get Environment (e.g. "nvim tmux" | "nvim" | "terminal" )
ENV=$(GetEnvironment)

# On nvim or not
if IsContained "$ENV" "nvim"; then
   IS_NVIM=0
else
   IS_NVIM=1
fi

# Execute Main()
Main
